theme: jekyll-theme-cayman
title: Michael Fey
name: Michael Fey
headline: Michael Fey
description: Husband, father, coder, climber, gamer, photographer. I am currently Head of End User Experience at 1Password. Find your way to all my stuff from here.
